[package]
name = "ka3005p"
version = "0.1.0"
authors = ["Nicola Coretti <nico.coretti@gmail.com>"]
edition = "2018"
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
structopt = "0.3.15"
human-panic = "1.0.3"

[[bin]]
name = "ka3005p"
path = "src/bin/ka3005p.rs"
